-- AlterEnum
ALTER TYPE "PayrollStatus" ADD VALUE IF NOT EXISTS 'PROCESSING';
ALTER TYPE "PayrollStatus" ADD VALUE IF NOT EXISTS 'COMPLETED';

-- AlterTable
ALTER TABLE "Employee" ADD COLUMN IF NOT EXISTS "salary" DOUBLE PRECISION NOT NULL DEFAULT 0;
